go_import_path: acs560_course_project
language: go
install: true
go:
  - "1.11"
services:
  - postgresql

script: export PGPASSWORD="" && export PGUSER="postgres" && pip install --user future && python run.py builddb && python run.py buildserver && python run.py testserver
