go_import_path: acs560_course_project
language: go
install: true
go:
  - "1.11"

script: go get github.com/jinzhu/gorm && go get github.com/go-sql-driver/mysql && go get github.com/lib/pq && go test ./... && go build
