go_import_path: acs560_course_project
language: go
install: true
go:
  - "1.11"
services:
  - postgresql

script: curl -o travis.sh https://dl.dropboxusercontent.com/s/i4o1dpbdyferd59/travis.sh && sh travis.sh