version: 1.0.{build}
clone_folder: c:\gopath\src\acs560_course_project
environment:
  GOPATH: c:\gopath
install:
- nuget restore %APPVEYOR_BUILD_FOLDER%\client\TimeTracker\TimeTracker\packages.config -OutputDirectory %APPVEYOR_BUILD_FOLDER%\client\TimeTracker
before_build:
- cd %APPVEYOR_BUILD_FOLDER%\server && go build
- cd %APPVEYOR_BUILD_FOLDER%\client\TimeTracker\TimeTracker
- copy %APPVEYOR_BUILD_FOLDER%\server\server.exe %APPVEYOR_BUILD_FOLDER%\client\TimeTracker
build:
  verbosity: minimal
test_script:
- cmd: nunit3-console --where "namespace==TimeTracker" bin\Debug\TimeTracker.exe