version: 1.0.{build}
clone_folder: c:\gopath\src\acs560_course_project
clone_depth: 1
environment:
  GOPATH: c:\gopath
cache:
- client\TimeTracker\packages -> **\packages.config
install:
- nuget restore %APPVEYOR_BUILD_FOLDER%\client\TimeTracker\TimeTracker\packages.config -OutputDirectory %APPVEYOR_BUILD_FOLDER%\client\TimeTracker\packages
before_build:
- go get github.com/jinzhu/gorm
- go get github.com/go-sql-driver/mysql
- go get github.com/lib/pq
- cd %APPVEYOR_BUILD_FOLDER%\server && go build
- cd %APPVEYOR_BUILD_FOLDER%\client\TimeTracker\TimeTracker
- copy %APPVEYOR_BUILD_FOLDER%\server\server.exe %APPVEYOR_BUILD_FOLDER%\client\TimeTracker
- dir %APPVEYOR_BUILD_FOLDER%\client\TimeTracker
build:
  verbosity: minimal
test_script:
- cmd: nunit3-console --where "namespace==TimeTracker" bin\Debug\TimeTracker.exe