version: 1.0.{build}
clone_folder: c:\gopath\src\acs560_course_project
clone_depth: 1
environment:
  GOPATH: c:\gopath
services:
  - postgresql
cache:
- client\TimeTracker\packages -> **\packages.config
install:
- pip install future
- nuget restore %APPVEYOR_BUILD_FOLDER%\client\TimeTracker\TimeTracker\packages.config -OutputDirectory %APPVEYOR_BUILD_FOLDER%\client\TimeTracker\packages
before_build:
- set PGUSER=postgres
- set PGPASSWORD=Password12!
- PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
- python run.py builddb
- python run.py buildserver
- python run.py testserver
build:
  verbosity: minimal
